language: go
sudo: false
go:
  - 1.10.x
before_install:
  - go get github.com/mattn/goveralls
script:
  - ulimit -n 1024 ; go test -v ./... -covermode=count -coverprofile=profile.cov.tmp
  - cat profile.cov.tmp | grep -v "_generated.go" > profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci