users:
  - username: guest
    password: $2a$14$OR8Od7QJ4yjck89RNWM0TeYJrQSIZLQ13ptktd3n.bStXuhZTcnuq # guest
tcp:
  nodelay: false
  readBufSize: 196608
  writeBufSize: 196608
queue:
  shardSize: 8192
db:
  defaultPath: db
  engine: badger
