users:
  - username: guest
#    password: $2a$14$OR8Od7QJ4yjck89RNWM0TeYJrQSIZLQ13ptktd3n.bStXuhZTcnuq # guest bcrypt
    password: 084e0343a0486ff05530df6c705c8bb4 # guest md5
tcp:
  nodelay: false
  readBufSize: 196608
  writeBufSize: 196608
connection:
  channelsMax: 4096
  frameMaxSize: 65536
queue:
  shardSize: 8192
db:
  defaultPath: db
  engine: badger
vhost:
  defaultPath: /
security:
  passwordCheck: md5